### ISSUE TITLE
What is the other.7z files?

### ISSUE THREAD

**Issue by debugyoshi** [MrL314/Project-L#2]
The guide says I need to add extra files to the setup folder. The files it refers to are located in other.7z. However I've searched everywhere, and there is no other.7z file here. If it's not meant to come with this, how would I get it? I don't know where these files would be found.

**Comment by Rexius55** [comment]
Search it up on archive.org. Find an upload of the Nintendo gigaleak that allows you to see about 56 files. You should find other.7z and be able to download it. There, you'll have to extract it and continue following the instructions. Also make sure to extract the .lzh files with 7-Zip, I misinterpreted the instructions at first lol!

**Comment by ElHave247** [comment]
> 

i give you the files, anyways im going to upload to my profile im not the author so i can upload what i want.
